import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    nav: {
      home: 'Home', about: 'About', testimonials: 'Testimonials', services: 'Our Service',
      team: 'Our Team', shop: 'Shop', arrivals: 'New Arrivals', track: 'Track Order', contact: 'Contact',
    },
    common: {
      search: 'Search shoes…', login: 'Login', signup: 'Sign Up', logout: 'Logout',
      dashboard: 'Dashboard', cart: 'Cart', viewAll: 'View all →', shopNow: 'Shop Now',
      addToCart: 'Add to Cart', view: 'View', outOfStock: 'Out of Stock', noSizes: 'No sizes',
      remove: 'Remove', continueShopping: 'Continue shopping', subtotal: 'Subtotal',
      deliveryFee: 'Delivery fee', total: 'Total', yourCart: 'Your Cart', size: 'Size',
      orders: 'Orders', profile: 'Profile', wishlist: 'Wishlist',
    },
    status: {
      PENDING: 'Pending', PROCESSING: 'Processing', SHIPPED: 'Shipped', DELIVERED: 'Delivered',
      COMPLETED: 'Completed', CANCELLED: 'Cancelled', PAID: 'Paid', FAILED: 'Failed',
    },
    hero: {
      badge: 'Quality Sport Shoes. Great Prices.',
      title: 'M&E PUB', subtitle: 'STEP INTO YOUR GAME.',
      shopNow: 'SHOP NOW →', whatsapp: 'WHATSAPP US', hot: 'Hot right now',
      styles: 'Styles', categories: 'Categories', quality: 'Quality',
    },
    footer: {
      tagline: 'Quality sport shoes and sneakers at great prices. Step into your game with MauzoPOS.',
      whatsapp: 'WhatsApp Us', shop: 'Shop', company: 'Company', findUs: 'Find Us',
      allShoes: 'All Shoes', featured: 'Featured', newArrivals: 'New Arrivals', bestSellers: 'Best Sellers',
      track: 'Track Your Order', about: 'About Us', contact: 'Contact',
      rights: 'All rights reserved.', developedBy: 'Developed by',
    },
    home: {
      shopByCategory: 'Shop by Category', products: 'products',
      newArrivals: 'New Arrivals', newArrivalsSub: 'Fresh drops — the latest to hit our shelves',
      featuredCollection: 'Featured Collection', featuredSub: 'Hand-picked favourites',
      bestSellers: 'Best Sellers', bestSellersSub: 'Loved by our customers',
    },
    shop: {
      title: 'SHOP ALL SHOES', productsAvailable: '{{n}} products available',
      searchPh: 'Search shoes…', allCategories: 'All Categories', allSizes: 'All Sizes',
      sortNewest: 'Newest', sortPriceAsc: 'Price: Low to High', sortPriceDesc: 'Price: High to Low',
      sortBestSellers: 'Best Sellers', noShoesFound: 'No shoes found',
      noShoesDesc: 'Try a different search or filter.', clearFilters: 'Clear filters',
      loadMore: 'Load more products',
    },
    product: {
      newArrival: 'New Arrival', bestSeller: 'Best Seller', featured: 'Featured',
      home: 'Home', shop: 'Shop', selectSize: 'Select Size',
      inStock: '{{n}} in stock', outOfStock: 'This size is out of stock',
      sizeGuide: '📏 Size Guide (EU)', us: 'US', uk: 'UK', footCm: 'Foot (cm)',
      sizeGuideHelp: 'Measure your foot from heel to longest toe, then match the length. If between sizes, go a half-size up. WhatsApp us on 0675029833 for sizing help.',
      quantity: 'Quantity', addToCart: '🛒 ADD TO CART', buyNow: 'BUY NOW',
      whatsappProduct: 'WHATSAPP ABOUT THIS PRODUCT',
      customerReviews: 'Customer Reviews ({{n}})',
      noReviews: 'No reviews yet. Be the first to review this product!',
      writeReview: 'Write a Review', rating: 'Rating', yourComment: 'Your comment',
      commentPh: 'How are the shoes?', addPhoto: 'Add a photo (optional)',
      photoAttached: 'Photo attached', submitReview: 'Submit Review',
      loginToReview: 'Login to write a review for purchased products.',
      customerPhoto: 'Customer photo', pleaseSelectSize: 'Please select a size',
      pleaseLoginCart: 'Please login to add items to your cart', pleaseLoginCheckout: 'Please login to checkout',
      addedToCart: 'Product added to cart ✓', thanksReview: 'Thanks for your review!',
      productNotFound: 'Product not found',
    },
    cart: {
      title: 'YOUR CART', emptyTitle: 'Your cart is empty',
      emptyDesc: 'Browse our shop and add some fresh shoes.', remove: 'Remove',
      clearCart: 'Clear cart', orderSummary: 'Order Summary', subtotal: 'Subtotal',
      deliveryFee: 'Delivery fee', total: 'Total', checkout: 'Checkout →',
      continueShopping: 'Continue shopping', size: 'Size',
      itemRemoved: 'Item removed from cart',
    },
    checkout: {
      stepDelivery: 'Delivery', stepPayment: 'Payment', stepDone: 'Done',
      emptyTitle: 'Your cart is empty', emptyDesc: 'Add some shoes first, then check out.',
      deliveryDetails: 'Delivery Details', fullName: 'Full name', phoneNumber: 'Phone number',
      email: 'Email', city: 'City', deliveryLocation: 'Delivery location',
      selectLocation: 'Select your location', street: 'Street / Location',
      streetPh: 'e.g. DIT, building 4', deliveryNotes: 'Delivery notes (optional)',
      notesPh: 'Any instructions for delivery', continueToPayment: 'Continue to Payment →',
      orderSummary: 'Order Summary', deliveryLabel: 'Delivery ({{zone}})',
      yourLocation: 'Your location', discount: 'Discount ({{code}})', promoApplied: 'Promo {{code}} applied',
      remove: 'Remove', promoCode: 'Promo code', apply: 'Apply',
      minOrder: 'Minimum order for this code is {{amount}}', promoAppliedMsg: 'Promo {{code}} applied!',
      choosePayment: 'Choose Payment Method', orderLine: 'Order {{number}} · Total {{total}}',
      cardPayment: 'Card Payment', cardNote: 'Credit / Debit card',
      processingPayment: 'Processing your sandbox payment…', reference: 'Reference: {{ref}}',
      simulated: 'This is a simulated payment for testing. No real money is charged.',
      pay: 'Pay {{amount}}', paymentSuccess: 'Payment Successful!',
      orderPaid: 'Your order {{number}} has been paid. A confirmation email is on its way.',
      totalPaid: 'Total paid', payment: 'Payment', weContact: 'We\'ll contact you on {{phone}} for delivery.',
      viewOrder: 'View Order', continueShopping: 'Continue Shopping',
      paymentFailed: 'Payment failed. Please try again.', paymentProcessing: 'Payment is still processing. Check your order status shortly.',
    },
    login: {
      title: 'Welcome back', subtitle: 'Login to your MauzoPOS account.',
      email: 'Email', password: 'Password', login: 'Login',
      welcomeBack: 'Welcome back, {{name}}!',
    },
    profile: {
      title: 'MY PROFILE', memberSince: 'Member since {{date}}', fullName: 'Full name',
      phoneNumber: 'Phone number', emailCannotChange: 'Email (cannot be changed)',
      save: 'Save Changes', updated: 'Profile updated ✓',
    },
    orders: {
      title: 'MY ORDERS', noOrders: 'No orders yet',
      noOrdersDesc: 'When you place an order it will appear here.', shopNow: 'Shop Now',
    },
    orderDetail: {
      myOrders: '← My orders', placed: 'Placed {{date}}',
      notPaid: 'This order is not paid yet.', completePayment: 'Complete payment to have your shoes shipped.',
      payNow: 'Pay now (Sandbox)', processing: 'Processing…',
      delivered: '🎉 Your parcel has been delivered!',
      youConfirmed: '✓ You confirmed delivery on {{date}}. We\'ll mark it complete shortly.',
      received: 'Received your shoes? Confirm delivery to complete your order.',
      confirming: 'Confirming…', confirmDelivery: 'Confirm Delivery',
      items: 'Items', subtotal: 'Subtotal', deliveryFee: 'Delivery fee', total: 'Total',
      delivery: 'Delivery', notes: 'Notes: {{notes}}', payments: 'Payments',
      paymentSuccess: 'Payment successful!', deliveryConfirmed: 'Delivery confirmed. Thank you!',
      paymentProcessing: 'Payment still processing. Try again shortly.',
    },
    track: {
      title: 'Track Your Order',
      subtitle: 'Enter the billing email you used at checkout and your Order ID from the confirmation email.',
      billingEmail: 'Billing email', orderId: 'Order ID', track: 'TRACK',
      placed: '{{name}} · Placed {{date}}', deliveryAddress: 'Delivery Address',
      items: 'Items', deliveryFee: 'Delivery fee', total: 'Total', notes: 'Notes: {{notes}}',
      sizeQty: '(Size {{size}} × {{qty}})',
    },
    timeline: {
      placed: 'Order Placed', processing: 'Processing', assigned: 'Assigned to Driver',
      delivered: 'Delivered', completed: 'Completed', cancelled: 'This order was cancelled',
      cancelledDesc: 'Contact us on WhatsApp for help.',
      currentStage: '{{stage}} is the current stage. Next: {{next}}.',
      orderCompleted: '🎉 Order completed. Enjoy your shoes!',
      confirmedByClient: '✓ Delivery confirmed by client {{date}}',
    },
    productCard: {
      new: 'New', bestSeller: 'Best Seller', outOfStock: 'Out of Stock',
      sizes: 'Sizes: {{sizes}}', noSizes: 'No sizes', addToCart: 'Add to Cart', view: 'View',
      added: 'Product added to cart ✓', loginToAdd: 'Please login to add items to your cart',
      outOfStockMsg: 'Product is currently out of stock',
    },
    homeSections: {
      shopNow: 'Shop Now', chatWhatsapp: 'Chat on WhatsApp',
    },
    services: {
      label: 'Our Service', title: 'SERVICE YOU CAN COUNT ON',
      subtitle: 'From Dar es Salaam to anywhere in Tanzania — we make buying sport shoes simple.',
      s1t: 'Fast Delivery in Dar es Salaam',
      s1d: 'Same-day delivery across Dar es Salaam and fast nationwide shipping. Order on WhatsApp or online and we get your shoes to you quickly.',
      s2t: 'Quality Guarantee',
      s2d: 'Every pair is checked before it leaves our shop at DIT, Morogoro Road. If something is wrong, we replace or refund — no long stories.',
      s3t: 'WhatsApp Ordering',
      s3d: 'Prefer to chat? Send us a message on WhatsApp, tell us your size and model, and we handle the rest. Payment on delivery available.',
      s4t: 'Size Exchange',
      s4d: 'Wrong size? No problem. Exchange any unworn pair within days of purchase, or visit us at Morogoro Road to try before you buy.',
      shopNow: 'Shop Now', chatWhatsapp: 'Chat on WhatsApp',
    },
    team: {
      label: 'Our Team', title: 'THE PEOPLE BEHIND MAUZOPOS',
      subtitle: 'A small, passionate team helping Tanzania play in the right shoes.',
      m1r: 'Founder & Sales Lead',
      m1d: 'Founded MauzoPOS at DIT with one mission — quality football boots at honest prices.',
      m2r: 'Operations & Warehouse',
      m2d: 'Keeps every order checked, packed and out the door fast from our Morogoro Road base.',
      m3r: 'Customer Care',
      m3d: 'Your first point of contact on WhatsApp — quick answers, size help and order updates.',
      cta: 'Want to work with us or visit the shop?', ctaLink: 'Message the team →',
    },
    testimonials: {
      label: 'Testimonials', title: 'WHAT OUR CUSTOMERS SAY',
      r1: 'Football player, Kinondoni',
      q1: 'I bought the MauzoPOS Predator FG for my Sunday league. The grip on the firm ground is unreal — scored twice on debut. Delivery to Kinondoni was same day!',
      r2: 'Running enthusiast, Mikocheni',
      q2: 'The Runner Pro is the comfiest shoe I have owned. Light, breathable and the price is way better than the big brands. MauzoPOS is now my go-to shop.',
      r3: 'Coach, Chang’ombe',
      q3: 'I ordered 12 pairs of Matchday TF for my academy players. The team communicated everything on WhatsApp and the boots lasted a full season.',
      r4: 'Futsal player, Buguruni',
      q4: 'The Court Indoor shoe is perfect for our futsal league. Non-marking soles, great grip, and my teammates keep asking where I got them!',
      r5: 'Gym owner, Posta',
      q5: 'I stock MauzoPOS Power Gym shoes for my members. Great quality, fair wholesale pricing and reliable restock. Highly recommend working with them.',
      r6: 'Customer, Mwenge',
      q6: 'Easy ordering on WhatsApp, quick delivery and they helped me exchange size with zero stress. Excellent service all round.',
    },
    newsletter: {
      title: 'JOIN THE MAUZOPOS VIP LIST', sub: 'Get new arrivals, special offers and exclusive MauzoPOS updates.',
      name: 'Your name', email: 'Email address', phone: 'Phone number (optional)',
      size: 'Your shoe size (optional)', agree: 'I agree to receive marketing emails from MauzoPOS.',
      subscribe: 'Subscribe — Join the VIP List', needConsent: 'Please agree to receive marketing emails',
      welcome: 'Welcome to the MauzoPOS VIP list! 👟',
      unsubTitle: 'Unsubscribe', unsubSub: 'Enter your email to stop receiving marketing emails.',
      unsubBtn: 'Unsubscribe', unsubDone: 'You\'re unsubscribed',
      unsubDoneSub: 'You won\'t receive marketing emails from MauzoPOS anymore.',
      unsubSeo: 'Unsubscribe — MauzoPOS',
    },
    contact: {
      title: 'CONTACT US', subtitle: 'We\'d love to hear from you.',
      visitStore: 'Visit Our Store', storeLine: 'M&E Pub · Mbeya, Isyesye',
      address: 'Address', whatsapp: 'WhatsApp', hours: 'Hours',
      hoursLine: 'Mon – Sat\n9:00 AM – 7:00 PM',
      sendMessage: 'Send us a message', reply: 'We reply to every message within one business day.',
      yourName: 'Your name', yourEmail: 'Your email', subject: 'Subject',
      subjectPh: 'Order question, sizing help, partnership…', message: 'Message', messagePh: 'How can we help?',
      send: 'Send Message', noteWhatsapp: 'Fastest way to reach us', noteEmail: 'For formal inquiries',
      noteInstagram: 'Follow our latest drops', noteTiktok: 'Behind the scenes', noteFacebook: 'Community updates',
    },
    about: {
      title: 'ABOUT M&E PUB', subtitle: 'Step into your game.',
      whoWeAre: 'Who we are',
      p1: 'MauzoPOS is a Dar es Salaam-based sports shoe and sneaker store located at DIT, Morogoro Road. We believe that great performance starts from the ground up — that\'s why we stock quality sport shoes for running, basketball, football, training and everyday wear at prices that make sense.',
      p2: 'Whether you\'re chasing a personal best, dominating the court, or just want a clean pair of sneakers for the streets — MauzoPOS has you covered. Browse our shop online, or reach us on WhatsApp and we\'ll help you find your perfect fit.',
      standFor: 'What we stand for',
      v1t: 'Quality First', v1d: 'Every pair we sell is chosen for durability, comfort and performance.',
      v2t: 'Great Prices', v2d: 'Real value for your money — quality sport shoes without the inflated markup.',
      v3t: 'Personal Service', v3d: 'Message us on WhatsApp any time. We help you pick the right fit.',
      v4t: 'Fast Delivery', v4d: 'Quick delivery across Dar es Salaam with careful packaging.',
      ready: 'Ready to step into your game?', shopNow: 'SHOP NOW', whatsappUs: 'WhatsApp Us',
    },
    wishlist: {
      title: 'MY WISHLIST', sub: 'Shoes you saved for later.',
      emptyTitle: 'Your wishlist is empty', emptyDesc: 'Tap the heart on any shoe to save it here.',
    },
    notFound: {
      title: 'Page not found', subtitle: 'The page you\'re looking for doesn\'t exist.',
      backHome: 'Back to Home',
    },
    error: {
      title: 'Something went wrong', retry: 'Try Again', home: 'Go Home',
      defaultSeo: 'M&E PUB — Step Into Your Game',
    },
    pos: {
      exp: {
        title: 'Expenses', today: "Today's Expenses", week: 'This Week', month: 'This Month',
        recTitle: 'Record Expense', category: 'Category', selectCat: 'Select a category…',
        amount: 'Amount (TZS)', date: 'Date', noteOpt: 'Note (optional)', notePh: 'Shop electricity',
        saveExpense: 'Save Expense',
        stockHint: 'Buying stock? Record it in {{inv}} → {{rec}}, not here — stock purchases are not operating expenses.',
        cats: 'Categories', noCats: 'No categories yet.', newCatPh: '+ New Category', add: 'Add',
        histTitle: 'Expense History', searchPh: 'Search expenses…', allCats: 'All categories', clear: 'Clear',
        noFound: 'No expenses found.',
        thDate: 'Date', thCategory: 'Category', thNote: 'Note', thAmount: 'Amount',
        thBy: 'Recorded By', thAction: 'Action', noNote: 'No note', view: 'View',
        detTitle: 'Expense Details', detCategory: 'Category', detAmount: 'Amount', detDate: 'Date',
        detBy: 'Recorded By', detNote: 'Note', edit: 'Edit', delete: 'Delete', saveChanges: 'Save changes',
        msgRecorded: 'Expense recorded ✓', msgCatAdded: 'Category added ✓', msgUpdated: 'Expense updated ✓',
        msgDeleted: 'Expense deleted ✓',
        delConfirm: 'Delete this {{amount}} expense? This will change net profit.',
      },
      debt: {
        title: 'Debt/Credit', recCredit: '+ Record Credit', creditSale: '+ Credit Sale',
        totalOutstanding: 'Total Outstanding',
        productsTaken: 'Products taken on credit', paidNow: 'Paid Now',
        total: 'Total', credit: 'Credit', addBtn: '+ Add',
        outstanding: 'Outstanding', customersOwing: 'Customers Owing', overdue: 'Overdue', dueSoon: 'Due Soon',
        searchPh: 'Search name or phone…', fAll: 'All', fOwing: 'Owing', fDueSoon: 'Due Soon',
        fOverdue: 'Overdue', fPaid: 'Paid',
        thCustomer: 'Customer', thPhone: 'Phone', thOutstanding: 'Outstanding', thDue: 'Due Date',
        thStatus: 'Status', thAction: 'Action',
        noPhone: 'No phone', dueOn: 'Due {{date}}', dueLate: '{{n}}d late', today: 'today', inDays: '{{n}}d',
        noDueDate: 'No due date', viewPay: 'View / Pay',
        nothingHere: 'Nothing here.', noDebts: 'No debts yet',
        noDebtsDesc: 'When you record a sale on credit, the customer and what they owe will appear here.',
        recTitle: 'Record Credit', customer: 'Customer', existing: 'Existing customer', newCustomer: '+ New Customer',
        selectCustomer: 'Select a customer…', owes: 'owes', newNamePh: 'Name *', newPhonePh: 'Phone (optional)',
        items: 'Items', searchProducts: 'Search products…',
        totalSale: 'Total sale', amountPaid: 'Amount paid', dueOpt: 'Due date (optional)',
        noteOpt: 'Note (optional)', notePh: 'Anything worth remembering',
        creditAmount: 'Credit amount', totalPaidLine: 'Total {{total}} − paid {{paid}}',
        cancel: 'Cancel', saveCredit: 'Save Credit',
        detOutstanding: 'Outstanding', detDue: 'due {{date}}', detNoDue: 'no due date',
        recordPayment: 'Record Payment', whatsapp: 'WhatsApp', copyMsg: 'Copy message',
        msgCopied: 'Message copied ✓', msgCopyFail: 'Could not copy the message',
        payPrev: 'Previous balance', payPay: 'Payment', payNew: 'New balance',
        detHistory: 'Debt History', paidAtSale: 'paid {{amount}} at sale',
        recordedBy: 'recorded by {{name}}', takenBy: 'taken by {{name}}',
        reverse: 'Reverse (wrong payment?)', reverseConfirm: 'Reverse this {{amount}} payment? The debt goes back up and the reversal is logged.',
        reversed: 'Payment reversed ✓', noHistory: 'No debt history for this customer.',
        currentBalance: 'Current Balance',
        payTitle: 'Record Payment', payOutstanding: 'Outstanding', payAmount: 'Payment amount',
        payAll: 'Pay all', payHalf: 'Half', payRemaining: 'Remaining after payment',
        payMethod: 'Payment method',
        msgEnterAmount: 'Enter a valid payment amount', msgTooMuch: 'Payment cannot be more than {{amount}}',
        msgPaid: 'Payment recorded ✓', msgPaidNew: 'Payment recorded ✓ new balance {{amount}}',
        msgItems: 'Add at least one item', msgNoDebt: 'Nothing would be left as debt — record a normal sale instead',
        msgNoDebtShop: 'Nothing would be left as debt — use Record Sale instead',
        msgEnterName: 'Enter the customer name', msgSelect: 'Select a customer',
        msgCreditRecorded: 'Credit recorded ✓ {{amount}} owed',
        remHello: 'Hello {{name}}, this is M&E Pub.', remBalance: 'Your outstanding balance is {{amount}}.',
        remDue: 'It was due on {{date}}.', remThanks: 'Please pay when you can. Thank you.',
        statusPaid: 'Paid', statusOwing: 'Owing', statusDueSoon: 'Due Soon', statusOverdue: 'Overdue',
      },
      inv: {
        title: 'Inventory', addProduct: '+ Add Product', receiveStock: 'Receive Stock',
        totalProducts: 'Total Products', lowStock: 'Low Stock', outOfStock: 'Out of Stock',
        expiringSoon: 'Expiring Soon', stockValue: 'Stock Value',
        requestedBy: 'Requested by shopkeeper', markDone: 'Mark done',
        alerts: 'Stock Alerts', allClear: 'Everything looks good — no stock needs attention. ✓',
        alertOut: 'Out of Stock', alertLow: 'Running Low', alertExp: 'Expiring Soon',
        nProducts: '{{n}} products', nProduct1: '{{n}} product',
        min: 'min', expires: 'expires', alreadyExpired: 'already expired', inDays: 'in {{n}} days',
        dLeft: '{{n}}d left', expired: 'expired',
        searchPh: 'Search products…', fAll: 'All', fLow: 'Low Stock', fOut: 'Out of Stock',
        fExpiring: 'Expiring', fRecent: 'Recently Added', noMatch: 'No products match.',
        thProduct: 'Product', thStock: 'Stock', thSell: 'Selling Price', thCost: 'Buying Cost',
        thProfit: 'Profit', thStatus: 'Status', thAction: 'Action',
        pack: 'Pack', receive: 'Receive', history: 'History', sell: 'Sell', cost: 'Cost',
        recSearchPh: 'Search product…', recPacks: 'Quantity (packs)', recPackPrice: 'Buying price per pack',
        recSupplier: 'Supplier (optional)', recExpiry: 'Expiry (optional)',
        recNotesPh: 'Invoice no, etc.', recNow: 'Now', recPackSize: 'Pack size', recDateAuto: 'Date: today (automatic)',
        recBack: 'Back', recTotal: 'Total cost',
        msgSelectProduct: 'Select a product first', msgEnterPacks: 'Enter how many packs',
        adjTitle: 'Adjust Stock', adjCurrent: 'Current stock', adjDelta: 'Adjustment (use − to reduce, e.g. −2)',
        adjReason: 'Reason', adjHint: 'Adjustments only correct stock — they never change sales revenue.',
        adjSave: 'Save adjustment', msgBadDelta: 'Enter a non-zero adjustment (e.g. -2)',
        detCurrent: 'Current Stock', detPack: 'Pack Size', detSell: 'Selling Price', detCost: 'Buying Cost',
        detProfitPer: 'Profit / {{u}}', detValue: 'Stock Value', detReceive: 'Receive Stock',
        detAdjust: 'Adjust Stock', detEdit: 'Edit Product', detActivity: 'Recent Activity',
        detNoMoves: 'No movements yet.',
        moveOpening: 'Opening stock', moveReceived: 'Stock received', moveSale: 'Sale',
        moveDamaged: 'Damaged', moveAdjustment: 'Adjustment',
        reasonDamaged: 'Damaged', reasonExpired: 'Expired', reasonMissing: 'Missing',
        reasonPersonal: 'Personal use', reasonCounting: 'Counting mistake', reasonOther: 'Other',
        msgReceived: 'Stock received ✓ +{{n}} {{u}}', msgAdjusted: 'Stock adjusted ✓ now {{n}} {{u}}',
        msgMarkedDone: 'Marked done ✓ — receive stock below to refill',
        msgProductGone: 'Product not found in inventory list',
        statusOut: 'Out of Stock', statusLow: 'Low Stock', statusOk: 'In Stock',
      },
      analytics: {
        title: 'Profit & Analytics', revChart: 'Revenue ({{r}})', netChart: 'Net profit ({{r}})',
        bestSelling: 'Best-selling (units)', highestRevenue: 'Highest revenue',
        mostProfitable: 'Most profitable', slowMoving: 'Slow-moving',
        sold: '{{n}} sold', noData: 'No data yet',
        thProduct: 'Product', thUnits: 'Units', thRevenue: 'Revenue', thCogs: 'COGS',
        thProfit: 'Profit', thMargin: 'Margin',
      },
      productForm: {
        addTitle: 'Add Product', editTitle: 'Edit Product', products: 'Products',
        name: 'Product name', namePh: 'e.g. Coca-Cola 500ml', description: 'Description',
        descPh: 'Describe the product…', sellPrice: 'Selling price (TZS)', buyPrice: 'Buying price (TZS)',
        unit: 'Unit', bundleQty: 'Bundle qty (units per purchase pack)', bundlePh: '24 for carton of 24',
        curStock: 'Current stock (units)', reorder: 'Reorder level', expiry: 'Expiry date (optional)',
        category: 'Category', unitCost: 'Unit cost', unitProfit: 'Unit profit',
        example: 'E.g. buy 1 carton (24 bottles) for 18,000 → unit cost 750 → sell at 1,000 → profit 250/unit.',
        sizesStock: 'Sizes & Stock', size: 'Size', totalStock: 'Total stock', pairs: 'pairs',
        images: 'Images', newImages: '{{n}} new image(s) selected',
        cancel: 'Cancel', save: 'Save Changes', create: 'Create Product',
        msgUpdated: 'Product updated ✓', msgCreated: 'Product created ✓',
      },
      dmgAdmin: {
        title: 'Damaged Stock', showReviewed: 'Show reviewed', hideReviewed: 'Hiding reviewed',
        nothingPending: 'Nothing awaiting review ✓', reviewed: 'reviewed ✓', markReviewed: 'Mark reviewed',
        msgReviewed: 'Marked reviewed ✓',
      },
      reports: {
        title: 'Reports', pdfTitle: 'Official PDF report — custom period',
        start: 'Start date', end: 'End date', secSales: 'Sales', secDebt: 'Debt/Credit', secStock: 'Stock',
        download: 'Download PDF', msgDates: 'Select a start and end date',
        msgOrder: 'End date cannot be before start date', msgSections: 'Select at least one report section',
        msgDownloaded: 'Report downloaded ✓',
        hint: 'Totals match the dashboard for the same period. Outstanding balances are current; sales and collections cover the selected dates.',
        closings: 'Daily closings', noClosings: 'No closing reports yet',
        noClosingsDesc: 'When a shopkeeper submits a daily closing, it will appear here for review.',
        thDate: 'Date', thShopkeeper: 'Shopkeeper', thExpected: 'Expected', thActual: 'Actual',
        thDiff: 'Diff', thReview: 'Review', review: 'Review', reviewed: 'Closing reviewed ✓',
        blkDaily: 'Daily report', blkSummary: '30-day summary', blkStock: 'Stock alert', blkExpiry: 'Expiry alert',
        noData: 'No data yet.', copyReport: 'Copy report',
      },
      activity: { title: 'Activity Log', system: 'System' },
      assistant: {
        title: 'MauzoOS AI Assistant', desc: 'Ask about your sales, stock, expenses, debt and business performance.',
        s1: 'How is the business doing today?', s2: 'How much did we sell today?',
        s3: 'Which products are running low?', s4: 'Who owes us money?', s5: 'What should I restock?',
        tryAsking: 'Try asking:', placeholder: 'Ask about your business…', send: 'Send',
        listening: 'Listening… speak now', thinking: 'Thinking…',
        micVoice: 'Voice input', micLang: 'Microphone language', mic: 'Mic',
        micUnsupported: 'Voice input is not supported in this browser — type your question instead.',
        micHear: 'Could not hear you — check the microphone permission, or type instead.',
        micBusy: 'Microphone is busy — try again.',
        aiFail: 'Sorry — I could not answer that right now. Your POS keeps working normally.',
      },
      dash: {
        title: 'Dashboard — today', sales: 'Sales', revenue: 'Revenue', gross: 'Gross profit',
        expenses: 'Expenses', net: 'Net profit', cogs: 'COGS', needsAttention: 'Needs attention',
        reorder: 'reorder {{r}}', pendingExpenses: '{{n}} pending expenses',
        unreviewedDamage: '{{n}} unreviewed damage',
        revChart: 'Revenue — last 7 days', netChart: 'Net profit — last 7 days',
      },
      admSales: {
        title: 'Sales', cardSales: 'Sales', cardRevenue: 'Revenue', cardGross: 'Gross profit',
        thDate: 'Date', thShopkeeper: 'Shopkeeper', thTotal: 'Total', thProfit: 'Profit', thAction: 'Action',
        view: 'View', invoice: 'Invoice', detTitle: 'Sale detail',
      },
      staff: {
        title: 'Staff accounts', fullName: 'Full name', email: 'Email', phone: 'Phone',
        password: 'Password', role: 'Role', optShop: 'Shopkeeper', optAdmin: 'Admin',
        add: 'Add staff', thName: 'Name', thEmail: 'Email', thPhone: 'Phone', thRole: 'Role',
        thStatus: 'Status', thAction: 'Action', admin: 'Admin', shopkeeper: 'Shopkeeper',
        you: '(you)', current: 'Current account', enable: 'Enable', disable: 'Disable',
        active: 'Active', disabled: 'Disabled',
        noStaff: 'No staff yet', noStaffDesc: 'Add your first team member above.',
        createdAdmin: 'Admin account created', createdShop: 'Shopkeeper account created',
        statusUpdated: 'Status updated',
      },
      products: {
        title: 'Products', add: '+ Add Product', searchPh: 'Search products…',
        noProducts: 'No products', noProductsDesc: 'Add your first product.',
        thProduct: 'Product', thCategory: 'Category', thBuying: 'Buying', thSelling: 'Selling',
        thStock: 'Stock', thActions: 'Actions', edit: 'Edit', delete: 'Delete',
        delTitle: 'Delete product', delConfirm: 'Are you sure you want to delete {{name}}? This cannot be undone.',
        cancel: 'Cancel', msgDeleted: 'Product deleted',
      },
      cats: {
        title: 'Categories', add: '+ Add Category', nProducts: '{{n}} product(s)',
        noDesc: 'No description', edit: 'Edit', delete: 'Delete',
        modalAdd: 'Add Category', modalEdit: 'Edit Category', name: 'Name', description: 'Description',
        saving: 'Saving…', save: 'Save',
        msgCreated: 'Category created ✓', msgUpdated: 'Category updated ✓',
        delConfirm: 'Delete category "{{name}}"?', msgDeleted: 'Category deleted',
      },
      dmg: {
        title: 'Report Damage', product: 'Product', select: 'Select…',
        quantity: 'Quantity', reason: 'Reason',
        rExpired: 'Expired', rDamaged: 'Damaged', rSpoiled: 'Spoiled',
        rBroken: 'Broken', rLost: 'Lost', rOther: 'Other',
        photo: 'Photo *', submit: 'Submit report',
        msgPhoto: 'Photo is required', msgReported: 'Damage reported ✓ stock updated',
      },
      closing: {
        title: 'Daily Closing', expected: "Expected (today's sales)", counted: 'Counted',
        cashLabel: 'Physical cash counted', cashPh: 'Count the drawer…',
        submit: 'Submit closing', msgSubmitted: 'Closing submitted ✓',
      },
      invoice: {
        back: 'Back', print: 'Print', receipt: 'Sales receipt', receiptNo: 'Receipt no',
        date: 'Date', item: 'Item', qty: 'Qty', price: 'Price', total: 'Total',
        thanks: 'Thank you for shopping with us!',
      },
      today: {
        revenueToday: 'Revenue today', sales: 'sales', noSales: 'No sales yet',
        firstSale: 'Record your first sale of the day.', sale: 'Sale',
        nLines: '{{n}} lines', tapInvoice: 'tap for invoice',
      },
      stock: {
        title: 'Stock', searchPh: 'Search…', noProducts: 'No products',
        noMatch: 'Nothing matches your search.', available: '{{n}} available', outOfStock: 'Out of stock',
      },
      common: {
        save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', back: 'Back',
        view: 'View', all: 'All', total: 'Total', date: 'Date', noteOpt: 'Note (optional)',
        search: 'Search…', loading: 'Loading…', confirm: 'Confirm', name: 'Name',
        phone: 'Phone', amount: 'Amount', status: 'Status', action: 'Action',
      },
      sale: {
        title: 'Record Sale', searchPh: 'Search product…', noProducts: 'No products',
        noMatch: 'Nothing matches your search.', outOfStock: 'Everything is out of stock.',
        left: '{{n}} left', inSale: 'In sale', qty: 'Qty', add: 'Add',
        confirmSale: 'Confirm sale', total: 'Total', payMethod: 'Payment method',
        mobRef: 'Mobile money reference', mobRefPh: 'e.g. MPK2X9F4K12 · transaction code',
        mobRefHint: 'Optional, but it makes reconciling against your M-Pesa statement much easier.',
        customer: 'Customer', existing: 'Existing', newCustomer: '+ New Customer',
        loadingCustomers: 'Loading customers…', noDebtors: 'No debtors registered yet — use + New Customer above.',
        selectCustomer: 'Select a customer…', alreadyOwes: 'This customer already owes {{amount}}.',
        owes: 'owes', custNamePh: 'Customer name *', phoneOpt: 'Phone (optional)',
        amountPaid: 'Amount paid', dueOpt: 'Due date (optional)',
        wTotal: 'Total', wPaid: 'paid', wDebt: 'debt',
        dueHint: 'Leave the due date empty if you did not promise a date. A debt with no due date is never marked overdue.',
        photoOpt: 'Evidence photo (optional)', photoReq: 'Evidence photo *',
        confirmBtn: 'Confirm sale · {{total}} · {{method}}',
        recordedDebt: 'Sale recorded ✓ debt {{amount}}', recorded: 'Sale recorded ✓ {{total}}',
        nItems: '{{n}} items',
        msgAddProduct: 'Add at least one product',
        msgFullPaid: 'Amount paid covers the whole total — use a normal sale instead',
        msgPhoto: 'Evidence photo is required',
        msgStockOnly: '{{name}}: only {{n}} in stock',
        msgEnterName: 'Enter the customer name',
        msgSelectDebtor: 'Select the customer taking the debt',
      },
      paymethods: { cash: 'Cash', mobile: 'Mobile Money', credit: 'Credit' },
      home: {
        title: 'Shopkeeper Home',
        tileSaleD: 'Fast sale with evidence photo', tileTodayD: 'Your sales today',
        tileStockD: 'Quantities only', tileDamageD: 'Damaged / expired',
        tileExpensesD: 'Record running costs', tileClosingD: 'Count cash vs expected',
        restockRequested: 'Restock requested ✓ admin notified',
        runningLow: 'Running low — request a restock',
        left: 'left', requested: 'Requested ✓', request: 'Request',
        viewAllStock: 'View all stock →', waitingApproval: 'Waiting for admin approval',
        expenses: 'expenses', expense1: 'expense', damageReports: 'damage reports', damageReport1: 'damage report',
      },
      login: {
        tagline: 'MauzoPOS · Simple POS for small shops',
        hero: 'Your whole shop, in one simple system.',
        heroSub: 'Sales, stock, debts and expenses — recorded in seconds, explained clearly, from any phone.',
        featSaleT: 'Fast sales', featSaleD: 'Record cash, mobile money and credit sales in seconds.',
        featStockT: 'Live inventory', featStockD: 'Stock levels, alerts and receiving, always up to date.',
        featRepT: 'Clear reports', featRepD: 'Profit, expenses and debts explained simply.',
      },
      nav: {
        dashboard: 'Dashboard', sales: 'Sales', analytics: 'Analytics', products: 'Products',
        categories: 'Categories', inventory: 'Inventory', expenses: 'Expenses', damage: 'Damage',
        debt: 'Debt/Credit', reports: 'Reports', assistant: 'AI Assistant', activity: 'Activity',
        staff: 'Staff', home: 'Home', recordSale: 'Record Sale', today: "Today's Sales",
        stock: 'Stock', reportDamage: 'Report Damage', dailyClosing: 'Daily Closing',
      },
      header: {
        adminPanel: 'Admin Panel', shopkeeper: 'Shopkeeper', welcome: 'Welcome, {{name}}',
        admin: 'Admin', shopkeeperFallback: 'Shopkeeper', newSale: 'New Sale', logout: 'Logout',
        lightMode: 'Light mode', darkMode: 'Dark mode',
      },
    },
    seo: {
      home: 'M&E PUB — Step Into Your Game',
      about: 'About Us — MauzoPOS',
      cart: 'Your Cart — MauzoPOS',
      checkout: 'Checkout — MauzoPOS',
      contact: 'Contact Us — MauzoPOS',
      login: 'Login — MauzoPOS',
      shop: 'Shop Shoes — MauzoPOS',
      track: 'Track Your Order — MauzoPOS',
      wishlist: 'My Wishlist — MauzoPOS',
      orders: 'My Orders — MauzoPOS',
      profile: 'My Profile — MauzoPOS',
      notFound: 'Page Not Found — MauzoPOS',
      orderDetail: 'Order {{number}} — MauzoPOS',
      product: '{{name}} — MauzoPOS',
    },
  },
  sw: {
    nav: {
      home: 'Nyumbani', about: 'Kuhusu', testimonials: 'Maoni', services: 'Huduma Zetu',
      team: 'Timu Yetu', shop: 'Duka', arrivals: 'Vitu Vipya', track: 'Fuatilia Agizo', contact: 'Wasiliana',
    },
    common: {
      search: 'Tafuta viatu…', login: 'Ingia', signup: 'Jisajili', logout: 'Toka',
      dashboard: 'Dashibodi', cart: 'Rukoba', viewAll: 'Angalia zote →', shopNow: 'Numua Sasa',
      addToCart: 'Ongeza kwenye Rukoba', view: 'Angalia', outOfStock: 'Imeisha', noSizes: 'Hakuna ukubwa',
      remove: 'Ondoa', continueShopping: 'Endelea kununua', subtotal: 'Jumla Ndogo',
      deliveryFee: 'Ada ya Uwasilishaji', total: 'Jumla', yourCart: 'Rukoba Wako', size: 'Ukubwa',
      orders: 'Maagizo', profile: 'Profili', wishlist: 'Orodha ya Ninavyopenda',
    },
    status: {
      PENDING: 'Inasubiri', PROCESSING: 'Inachakatwa', SHIPPED: 'Imesafirishwa', DELIVERED: 'Imefikishwa',
      COMPLETED: 'Imekamilika', CANCELLED: 'Imesitishwa', PAID: 'Imelipwa', FAILED: 'Imeshindikana',
    },
    hero: {
      badge: 'Viatu vya Ubora. Bei Nzuri.',
      title: 'M&E PUB', subtitle: 'INGIA KATIKA MWENZAKO.',
      shopNow: 'NUMUA SASA →', whatsapp: 'WHATSAPP', hot: 'Moto sasa',
      styles: 'Mitindo', categories: 'Kategoria', quality: 'Ubora',
    },
    footer: {
      tagline: 'Viatu vya ubora kwa bei nzuri. Ingia katika mchezo wako na MauzoPOS.',
      whatsapp: 'WhatsApp Sisi', shop: 'Duka', company: 'Kampuni', findUs: 'Tupate',
      allShoes: 'Viatu Vyote', featured: 'Mpangilio', newArrivals: 'Vitu Vipya', bestSellers: 'Vinauzika Sana',
      track: 'Fuatilia Agizo Lako', about: 'Kuhusu Sisi', contact: 'Wasiliana',
      rights: 'Haki zote zimehifadhiwa.', developedBy: 'Imeandaliwa na',
    },
    home: {
      shopByCategory: 'Nunua kwa Kategoria', products: 'bidhaa',
      newArrivals: 'Vitu Vipya', newArrivalsSub: 'Mtindo mpya — vitu vya hivi punde kwenye maduka yetu',
      featuredCollection: 'Mkusanyiko uliochaguliwa', featuredSub: 'Vipendwa vilivyochaguliwa kwa makini',
      bestSellers: 'Vinauzika Sana', bestSellersSub: 'Vinavyopendwa na wateja wetu',
    },
    shop: {
      title: 'VIATU VYOTE', productsAvailable: 'Bidhaa {{n}} zinapatikana',
      searchPh: 'Tafuta viatu…', allCategories: 'Kategoria Zote', allSizes: 'Ukubwa Wote',
      sortNewest: 'Mpya Kabisa', sortPriceAsc: 'Bei: Ya Chini Hadi Juu', sortPriceDesc: 'Bei: Ya Juu Hadi Chini',
      sortBestSellers: 'Vinauzika Sana', noShoesFound: 'Hakuna viatu vilivyopatikana',
      noShoesDesc: 'Jaribu utafutaji au kichujio kingine.', clearFilters: 'Futa vichujio',
      loadMore: 'Onyesha bidhaa zaidi',
    },
    product: {
      newArrival: 'Kipya', bestSeller: 'Kinauzika Sana', featured: 'Kilichochaguliwa',
      home: 'Nyumbani', shop: 'Duka', selectSize: 'Chagua Ukubwa',
      inStock: '{{n}} zipo', outOfStock: 'Ukubwa huu umeisha',
      sizeGuide: '📏 Mwongozo wa Ukubwa (EU)', us: 'US', uk: 'UK', footCm: 'Urefu wa mguu (cm)',
      sizeGuideHelp: 'Pima mguu wako kutoka kisigino hadi kidole kirefu, kisha linganisha urefu. Ukikuta kati ya ukubwa, chukua nusu kubwa zaidi. WhatsApp sisi kwa 0675029833 kwa usaidizi wa ukubwa.',
      quantity: 'Kiasi', addToCart: '🛒 ONGEZA KWENYE RUKOBA', buyNow: 'NUMUA SASA',
      whatsappProduct: 'WHATSAPP KUHUSU BIDHAA HII',
      customerReviews: 'Maoni ya Wateja ({{n}})',
      noReviews: 'Hakuna maoni bado. Kuwa wa kwanza kutoa maoni kuhusu bidhaa hii!',
      writeReview: 'Andika Maoni', rating: 'Alama', yourComment: 'Maoni yako',
      commentPh: 'Viatu viko vipi?', addPhoto: 'Ongeza picha (hiari)',
      photoAttached: 'Picha imeambatishwa', submitReview: 'Tuma Maoni',
      loginToReview: 'Ingia kuandika maoni kwa bidhaa ulizonunua.',
      customerPhoto: 'Picha ya mteja', pleaseSelectSize: 'Tafadhali chagua ukubwa',
      pleaseLoginCart: 'Tafadhali ingia ili kuongeza bidhaa kwenye rukoba', pleaseLoginCheckout: 'Tafadhali ingia kufanya malipo',
      addedToCart: 'Bidhaa imeongezwa kwenye rukoba ✓', thanksReview: 'Asante kwa maoni yako!',
      productNotFound: 'Bidhaa haikupatikana',
    },
    cart: {
      title: 'RUKOBA WAKO', emptyTitle: 'Rukoba lako halina bidhaa',
      emptyDesc: 'Tazama duka letu na ongeza viatu vipya.', remove: 'Ondoa',
      clearCart: 'Futa rukoba', orderSummary: 'Muhtasari wa Agizo', subtotal: 'Jumla Ndogo',
      deliveryFee: 'Ada ya Uwasilishaji', total: 'Jumla', checkout: 'Fanya Malipo →',
      continueShopping: 'Endelea kununua', size: 'Ukubwa',
      itemRemoved: 'Bidhaa imeondolewa kwenye rukoba',
    },
    checkout: {
      stepDelivery: 'Uwasilishaji', stepPayment: 'Malipo', stepDone: 'Imekamilika',
      emptyTitle: 'Rukoba lako halina bidhaa', emptyDesc: 'Ongeza viatu kwanza, kisha fanya malipo.',
      deliveryDetails: 'Maelezo ya Uwasilishaji', fullName: 'Jina kamili', phoneNumber: 'Namba ya simu',
      email: 'Barua pepe', city: 'Mji', deliveryLocation: 'Eneo la uwasilishaji',
      selectLocation: 'Chagua eneo lako', street: 'Mtaa / Mahali',
      streetPh: 'mf. DIT, jengo 4', deliveryNotes: 'Ujumbe wa uwasilishaji (hiari)',
      notesPh: 'Maelekezo yoyote ya uwasilishaji', continueToPayment: 'Endelea kwa Malipo →',
      orderSummary: 'Muhtasari wa Agizo', deliveryLabel: 'Uwasilishaji ({{zone}})',
      yourLocation: 'Mahali pako', discount: 'Punguzo ({{code}})', promoApplied: 'Promo {{code}} imetumika',
      remove: 'Ondoa', promoCode: 'Msimbo wa promo', apply: 'Tumia',
      minOrder: 'Agizo la chini kwa msimbo huu ni {{amount}}', promoAppliedMsg: 'Promo {{code}} imetumika!',
      choosePayment: 'Chagua Njia ya Malipo', orderLine: 'Agizo {{number}} · Jumla {{total}}',
      cardPayment: 'Malipo ya Kadi', cardNote: 'Kadi ya mkopo / kadi ya benki',
      processingPayment: 'Tunachakata malipo yako ya mtihani…', reference: 'Rejea: {{ref}}',
      simulated: 'Huu ni malipo ya kujaribu tu. Hakuna pesa halisi zinazotozwa.',
      pay: 'Lipa {{amount}}', paymentSuccess: 'Malipo Yamefanikiwa!',
      orderPaid: 'Agizo lako {{number}} limelipwa. Barua pepe ya uthibitisho inaelekea kwako.',
      totalPaid: 'Jumla iliyolipwa', payment: 'Malipo', weContact: 'Tutawasiliana nawe kwa {{phone}} kwa ajili ya uwasilishaji.',
      viewOrder: 'Angalia Agizo', continueShopping: 'Endelea Kununua',
      paymentFailed: 'Malipo yameshindikana. Tafadhali jaribu tena.', paymentProcessing: 'Malipo bado yanachakatwa. Angalia hali ya agizo lako baadaye.',
    },
    login: {
      title: 'Karibu tena', subtitle: 'Ingia kwenye akaunti yako ya MauzoPOS.',
      email: 'Barua pepe', password: 'Nenosiri', login: 'Ingia',
      welcomeBack: 'Karibu tena, {{name}}!',
    },
    profile: {
      title: 'PROFILI YANGU', memberSince: 'Mwanachama tangu {{date}}', fullName: 'Jina kamili',
      phoneNumber: 'Namba ya simu', emailCannotChange: 'Barua pepe (haiwezi kubadilishwa)',
      save: 'Hifadhi Mabadiliko', updated: 'Profili imesasishwa ✓',
    },
    orders: {
      title: 'MAAGIZO YANGU', noOrders: 'Bado hakuna maagizo',
      noOrdersDesc: 'Ukitoa agizo litaonekana hapa.', shopNow: 'Numua Sasa',
    },
    orderDetail: {
      myOrders: '← Maagizo yangu', placed: 'Uliwekwa {{date}}',
      notPaid: 'Agizo hili halijalipwa bado.', completePayment: 'Kamilisha malipo ili viatu vyako viweze kusafirishwa.',
      payNow: 'Lipa sasa (Sandbox)', processing: 'Tunachakata…',
      delivered: '🎉 Kifurushi chako kimefika!',
      youConfirmed: '✓ Umethibitisha uwasilishaji {{date}}. Tutaalika kukamilisha hivi karibuni.',
      received: 'Umepokea viatu? Thibitisha uwasilishaji ili kukamilisha agizo lako.',
      confirming: 'Tunathibitisha…', confirmDelivery: 'Thibitisha Uwasilishaji',
      items: 'Bidhaa', subtotal: 'Jumla Ndogo', deliveryFee: 'Ada ya Uwasilishaji', total: 'Jumla',
      delivery: 'Uwasilishaji', notes: 'Ujumbe: {{notes}}', payments: 'Malipo',
      paymentSuccess: 'Malipo yamefanikiwa!', deliveryConfirmed: 'Uwasilishaji umethibitishwa. Asante!',
      paymentProcessing: 'Malipo bado yanachakatwa. Jaribu tena baadaye.',
    },
    track: {
      title: 'Fuatilia Agizo Lako',
      subtitle: 'Weka barua pepe uliyotumia kwenye malipo na Namba ya Agizo kutoka barua pepe ya uthibitisho.',
      billingEmail: 'Barua pepe ya malipo', orderId: 'Namba ya Agizo', track: 'FUATILIA',
      placed: '{{name}} · Uliwekwa {{date}}', deliveryAddress: 'Anwani ya Uwasilishaji',
      items: 'Bidhaa', deliveryFee: 'Ada ya Uwasilishaji', total: 'Jumla', notes: 'Ujumbe: {{notes}}',
      sizeQty: '(Ukubwa {{size}} × {{qty}})',
    },
    timeline: {
      placed: 'Agizo Limewekwa', processing: 'Inachakatwa', assigned: 'Limekabidhiwa kwa Dereva',
      delivered: 'Limefikishwa', completed: 'Limekamilika', cancelled: 'Agizo hili limesitishwa',
      cancelledDesc: 'Wasiliana nasi kwa WhatsApp kwa usaidizi.',
      currentStage: '{{stage}} ndiyo hatua ya sasa. Inayofuata: {{next}}.',
      orderCompleted: '🎉 Agizo limekamilika. Furahia viatu vyako!',
      confirmedByClient: '✓ Uwasilishaji umethibitishwa na mteja {{date}}',
    },
    productCard: {
      new: 'Mpya', bestSeller: 'Kinauzika Sana', outOfStock: 'Imeisha',
      sizes: 'Ukubwa: {{sizes}}', noSizes: 'Hakuna ukubwa', addToCart: 'Ongeza kwenye Rukoba', view: 'Angalia',
      added: 'Bidhaa imeongezwa kwenye rukoba ✓', loginToAdd: 'Tafadhali ingia ili kuongeza bidhaa kwenye rukoba',
      outOfStockMsg: 'Bidhaa imeisha kwa sasa',
    },
    homeSections: {
      shopNow: 'Numua Sasa', chatWhatsapp: 'Ongea kwa WhatsApp',
    },
    services: {
      label: 'Huduma Zetu', title: 'HUDUMA UNAYOIAMINI',
      subtitle: 'Kutoka Dar es Salaam hadi kwingineko Tanzania — tunarahisisha ununuzi wa viatu vya michezo.',
      s1t: 'Uwasilishaji wa Haraka Dar es Salaam',
      s1d: 'Uwasilishaji wa siku hiyo hiyo Dar es Salaam na usafirishaji wa haraka nchini kote. Agiza kwa WhatsApp au mtandaoni na tutafikisha viatu vyako haraka.',
      s2t: 'Dhamana ya Ubora',
      s2d: 'Kila jozi hukaguliwa kabla ya kuondoka dukani kwetu DIT, Morogoro Road. Kama kuna tatizo, tunabadilisha au kurejesha fedha — bila maneno mengi.',
      s3t: 'Kuagiza kwa WhatsApp',
      s3d: 'Unapenda kuongea? Tutumie ujumbe WhatsApp, tuambie ukubwa wako na mfano, na sisi tutashughulikia yote. Malipo ya mkononi yanapatikana.',
      s4t: 'Kubadilishana Ukubwa',
      s4d: 'Ukubwa usiofaa? Hakuna shida. Badilisha jozi yoyote isiyotumika ndani ya siku chache baada ya kununua, au tutembelee Morogoro Road ujaribu kabla ya kununua.',
      shopNow: 'Numua Sasa', chatWhatsapp: 'Ongea kwa WhatsApp',
    },
    team: {
      label: 'Timu Yetu', title: 'WATU WALIO NYUMA YA MAUZOPOS',
      subtitle: 'Timu ndogo yenye shauku inayosaidia Tanzania kucheza kwa viatu sahihi.',
      m1r: 'Mwanzilishi na Meneja wa Mauzo',
      m1d: 'Alianzisha MauzoPOS DIT kwa lengo moja — buti za mpira bora kwa bei ya uaminifu.',
      m2r: 'Uendeshaji na Ghala',
      m2d: 'Anahakikisha kila agizo linakaguliwa, kufungwa na kutoka haraka kutoka kituo chetu cha Morogoro Road.',
      m3r: 'Huduma kwa Wateja',
      m3d: 'Njia yako ya kwanza ya mawasiliano kwa WhatsApp — majibu ya haraka, usaidizi wa ukubwa na taarifa za agizo.',
      cta: 'Unataka kufanya kazi nasi au kutembelea duka?', ctaLink: 'Tuma ujumbe kwa timu →',
    },
    testimonials: {
      label: 'Maoni', title: 'WATEJA WETU WANASEMA NINI',
      r1: 'Mchezaji wa mpira, Kinondoni',
      q1: 'Nilinunua MauzoPOS Predator FG kwa ligi yangu ya Jumapili. Kushikia kwenye ardhi ngumu ni ajabu — nimefunga mara mbili kwenye mechi ya kwanza. Uwasilishaji Kinondoni ulikuwa siku hiyo hiyo!',
      r2: 'Mwanariadha wa kukimbia, Mikocheni',
      q2: 'Runner Pro ni kiatu kizuri zaidi nimewahi kuwa nacho. Kipapu, kinapumua na bei ni bora kuliko chapa kubwa. MauzoPOS sasa ni duka langu la kwanza.',
      r3: 'Kocha, Chang’ombe',
      q3: 'Niliagiza jozi 12 za Matchday TF kwa wachezaji wa akademia yangu. Timu iliwasiliana kila kitu kwa WhatsApp na buti zilidumu msimu mzima.',
      r4: 'Mchezaji wa futsal, Buguruni',
      q4: 'Court Indoor ni kamili kwa ligi yetu ya futsal. Soli zisizoacha alama, kushikia vizuri, na wenzangu wanaendelea kuuliza nilizipata wapi!',
      r5: 'Mwenye gym, Posta',
      q5: 'Ninauza viatu vya MauzoPOS Power Gym kwa wanachama wangu. Ubora mzuri, bei nzuri za jumla na kujazwa tena kwa uhakika. Ninapendekeza kufanya kazi nao.',
      r6: 'Mteja, Mwenge',
      q6: 'Kuagiza kwa WhatsApp ni rahisi, uwasilishaji wa haraka na walinisaidia kubadilisha ukubwa bila shida yoyote. Huduma bora kabisa.',
    },
    newsletter: {
      title: 'JIUNGE NA ORODHA YA MAUZOPOS VIP', sub: 'Pata vitu vipya, ofa maalum na taarifa za kipekee za MauzoPOS.',
      name: 'Jina lako', email: 'Barua pepe', phone: 'Namba ya simu (hiari)',
      size: 'Ukubwa wako wa viatu (hiari)', agree: 'Nakubali kupokea barua pepe za matangazo kutoka MauzoPOS.',
      subscribe: 'Jiunge — Ingia kwenye Orodha ya VIP', needConsent: 'Tafadhali kubali kupokea barua pepe za matangazo',
      welcome: 'Karibu kwenye orodha ya MauzoPOS VIP! 👟',
      unsubTitle: 'Jiondoe kwenye Orodha', unsubSub: 'Weka barua pepe yako ili usipokee tena barua pepe za matangazo.',
      unsubBtn: 'Jiondoe', unsubDone: 'Umejiondoa',
      unsubDoneSub: 'Hutapokea tena barua pepe za matangazo kutoka MauzoPOS.',
      unsubSeo: 'Jiondoe kwenye Orodha — MauzoPOS',
    },
    contact: {
      title: 'WASILIANA NASI', subtitle: 'Tunapenda kusikia kutoka kwako.',
      visitStore: 'Tembelea Duka Letu', storeLine: 'M&E Pub · Mbeya, Isyesye',
      address: 'Anwani', whatsapp: 'WhatsApp', hours: 'Saa za Kazi',
      hoursLine: 'Jumatatu – Jumamosi\n9:00 asubuhi – 7:00 jioni',
      sendMessage: 'Tutumie ujumbe', reply: 'Tunajibu kila ujumbe ndani ya siku moja ya kazi.',
      yourName: 'Jina lako', yourEmail: 'Barua pepe yako', subject: 'Mada',
      subjectPh: 'Swali la agizo, usaidizi wa ukubwa, ushirikiano…', message: 'Ujumbe', messagePh: 'Tunawezaje kusaidia?',
      send: 'Tuma Ujumbe', noteWhatsapp: 'Njia ya haraka zaidi kutufikia', noteEmail: 'Kwa maswali rasmi',
      noteInstagram: 'Fuata mtindo wetu wa hivi punde', noteTiktok: 'Nyuma ya pazia', noteFacebook: 'Taarifa za jamii',
    },
    about: {
      title: 'KUHUSU M&E PUB', subtitle: 'Ingia katika mchezo wako.',
      whoWeAre: 'Sisi ni nani',
      p1: 'MauzoPOS ni duka la viatu vya michezo na sneakers lililopo Dar es Salaam, DIT, Morogoro Road. Tunaamini mafanikio makubwa huanza kutoka chini — ndiyo maana tunauza viatu bora vya michezo kwa kukimbia, mpira wa kikapu, mpira wa miguu, mazoezi na matumizi ya kila siku kwa bei nzuri.',
      p2: 'Iwe unafuata rekodi yako binafsi, unatawala uwanja, au unataka tu jozi safi ya sneakers kwa mitaa — MauzoPOS inakuhudumia. Vinjari duka letu mtandaoni, au wasiliana nasi kwa WhatsApp na tutakusaidia kupata ukubwa wako kamili.',
      standFor: 'Tunachosimamia',
      v1t: 'Ubora wa Kwanza', v1d: 'Kila jozi tunayouza imechaguliwa kwa kudumu, raha na utendaji.',
      v2t: 'Bei Nzuri', v2d: 'Thamani halisi ya pesa zako — viatu bora vya michezo bila bei za juu kupita kiasi.',
      v3t: 'Huduma Binafsi', v3d: 'Tutumie ujumbe WhatsApp wakati wowote. Tunakusaidia kuchagua ukubwa sahihi.',
      v4t: 'Uwasilishaji wa Haraka', v4d: 'Uwasilishaji wa haraka kote Dar es Salaam kwa ufungaji makini.',
      ready: 'Uko tayari kuingia katika mchezo wako?', shopNow: 'NUMUA SASA', whatsappUs: 'WhatsApp Sisi',
    },
    wishlist: {
      title: 'ORODHA YA NINAVYOPENDA', sub: 'Viatu ulivyohifadhi kwa baadaye.',
      emptyTitle: 'Orodha yako ya kupenda haina bidhaa', emptyDesc: 'Bonyeza moyo kwenye kiatu chochote kuihifadhi hapa.',
    },
    notFound: {
      title: 'Ukurasa haukupatikana', subtitle: 'Ukurasa unaoutafuta haupo.',
      backHome: 'Rudi Nyumbani',
    },
    error: {
      title: 'Kuna tatizo limetokea', retry: 'Jaribu Tena', home: 'Rudi Nyumbani',
      defaultSeo: 'M&E PUB — Ingia Katika Mchezo Wako',
    },
    pos: {
      exp: {
        title: 'Gharama', today: 'Gharama za Leo', week: 'Wiki Hii', month: 'Mwezi Huu',
        recTitle: 'Rekodi Gharama', category: 'Kipengele', selectCat: 'Chagua kipengele…',
        amount: 'Kiasi (TZS)', date: 'Tarehe', noteOpt: 'Maelezo (hiari)', notePh: 'Umeme wa dukani',
        saveExpense: 'Hifadhi Gharama',
        stockHint: 'Unanunua stoo? Rekodi kwenye {{inv}} → {{rec}}, si hapa — manunuzi ya stoo si gharama za uendeshaji.',
        cats: 'Vipengele', noCats: 'Hakuna vipengele bado.', newCatPh: '+ Kipengele Kipya', add: 'Ongeza',
        histTitle: 'Historia ya Gharama', searchPh: 'Tafuta gharama…', allCats: 'Vipengele vyote', clear: 'Futa',
        noFound: 'Hakuna gharama zilizopatikana.',
        thDate: 'Tarehe', thCategory: 'Kipengele', thNote: 'Maelezo', thAmount: 'Kiasi',
        thBy: 'Aliyerekodi', thAction: 'Kitendo', noNote: 'Hakuna maelezo', view: 'Angalia',
        detTitle: 'Maelezo ya Gharama', detCategory: 'Kipengele', detAmount: 'Kiasi', detDate: 'Tarehe',
        detBy: 'Aliyerekodi', detNote: 'Maelezo', edit: 'Hariri', delete: 'Futa', saveChanges: 'Hifadhi mabadiliko',
        msgRecorded: 'Gharama imerekodiwa ✓', msgCatAdded: 'Kipengele kimeongezwa ✓', msgUpdated: 'Gharama imesasishwa ✓',
        msgDeleted: 'Gharama imefutwa ✓',
        delConfirm: 'Futa gharama hii ya {{amount}}? Hii itabadilisha faida halisi.',
      },
      debt: {
        title: 'Deni/Mkopo', recCredit: '+ Rekodi Mkopo', creditSale: '+ Mauzo ya Mkopo',
        totalOutstanding: 'Jumla ya Madeni',
        productsTaken: 'Bidhaa zilizochukuliwa kwa mkopo', paidNow: 'Amelipa Sasa',
        total: 'Jumla', credit: 'Mkopo', addBtn: '+ Ongeza',
        outstanding: 'Deni', customersOwing: 'Wateja Wanaodaiwa', overdue: 'Zimechelewa', dueSoon: 'Zinakaribia',
        searchPh: 'Tafuta jina au simu…', fAll: 'Zote', fOwing: 'Deni', fDueSoon: 'Zinakaribia',
        fOverdue: 'Zimechelewa', fPaid: 'Zimelipwa',
        thCustomer: 'Mteja', thPhone: 'Simu', thOutstanding: 'Deni', thDue: 'Tarehe',
        thStatus: 'Hali', thAction: 'Kitendo',
        noPhone: 'Hakuna simu', dueOn: 'Tarehe {{date}}', dueLate: 'siku {{n}}', today: 'leo', inDays: 'siku {{n}}',
        noDueDate: 'Hakuna tarehe', viewPay: 'Angalia / Lipa',
        nothingHere: 'Hakuna chochote hapa.', noDebts: 'Hakuna madeni bado',
        noDebtsDesc: 'Unaporekodi mauzo kwa mkopo, mteja na deni lake vitaonekana hapa.',
        recTitle: 'Rekodi Mkopo', customer: 'Mteja', existing: 'Mteja aliyepo', newCustomer: '+ Mteja Mpya',
        selectCustomer: 'Chagua mteja…', owes: 'anadaiwa', newNamePh: 'Jina *', newPhonePh: 'Simu (hiari)',
        items: 'Bidhaa', searchProducts: 'Tafuta bidhaa…',
        totalSale: 'Jumla ya mauzo', amountPaid: 'Kiasi kilicholipwa', dueOpt: 'Tarehe ya kulipa (hiari)',
        noteOpt: 'Maelezo (hiari)', notePh: 'Chochote cha kukumbuka',
        creditAmount: 'Kiasi cha mkopo', totalPaidLine: 'Jumla {{total}} − amelipa {{paid}}',
        cancel: 'Ghairi', saveCredit: 'Hifadhi Mkopo',
        detOutstanding: 'Deni', detDue: 'tarehe {{date}}', detNoDue: 'hakuna tarehe',
        recordPayment: 'Rekodi Malipo', whatsapp: 'WhatsApp', copyMsg: 'Nakili ujumbe',
        msgCopied: 'Ujumbe umenakiliwa ✓', msgCopyFail: 'Ujumbe haukunakiliwa',
        payPrev: 'Salio la awali', payPay: 'Malipo', payNew: 'Salio jipya',
        detHistory: 'Historia ya Deni', paidAtSale: 'amelipa {{amount}} wakati wa mauzo',
        recordedBy: 'amerekodi {{name}}', takenBy: 'amepokea {{name}}',
        reverse: 'Rejesha (malipo yalikosewa?)', reverseConfirm: 'Rejesha malipo haya ya {{amount}}? Deni litarudi juu na urejeshaji utarekodiwa.',
        reversed: 'Malipo yamerejeshwa ✓', noHistory: 'Hakuna historia ya deni kwa mteja huyu.',
        currentBalance: 'Salio la Sasa',
        payTitle: 'Rekodi Malipo', payOutstanding: 'Deni', payAmount: 'Kiasi cha malipo',
        payAll: 'Lipa yote', payHalf: 'Nusu', payRemaining: 'Kitakachobaki baada ya malipo',
        payMethod: 'Njia ya malipo',
        msgEnterAmount: 'Weka kiasi sahihi cha malipo', msgTooMuch: 'Malipo hayawezi kuzidi {{amount}}',
        msgPaid: 'Malipo yamekamilika ✓', msgPaidNew: 'Malipo yamekamilika ✓ salio jipya {{amount}}',
        msgItems: 'Ongeza bidhaa angalau moja', msgNoDebt: 'Hakuna kitakachobaki kama deni — rekodi mauzo ya kawaida',
        msgNoDebtShop: 'Hakuna kitakachobaki kama deni — tumia Rekodi Mauzo',
        msgEnterName: 'Weka jina la mteja', msgSelect: 'Chagua mteja',
        msgCreditRecorded: 'Mkopo umerekodiwa ✓ {{amount}} inadaiwa',
        remHello: 'Habari {{name}}, hii ni M&E Pub.', remBalance: 'Deni lako lililobaki ni {{amount}}.',
        remDue: 'Lilitakiwa kulipwa {{date}}.', remThanks: 'Tafadhali lipa unapoweza. Asante.',
        statusPaid: 'Imelipwa', statusOwing: 'Deni', statusDueSoon: 'Karibia', statusOverdue: 'Zimechelewa',
      },
      inv: {
        title: 'Stoo', addProduct: '+ Ongeza Bidhaa', receiveStock: 'Pokea Stoo',
        totalProducts: 'Jumla ya Bidhaa', lowStock: 'Stoo Ndogo', outOfStock: 'Zimeisha',
        expiringSoon: 'Zinakaribia Kuisha', stockValue: 'Thamani ya Stoo',
        requestedBy: 'Muuzaji ameomba stoo', markDone: 'Maliza',
        alerts: 'Arifa za Stoo', allClear: 'Hakuna tatizo — stoo iko sawa. ✓',
        alertOut: 'Zimeisha', alertLow: 'Zinapungua', alertExp: 'Zinakaribia kuisha',
        nProducts: 'bidhaa {{n}}', nProduct1: 'bidhaa {{n}}',
        min: 'chini', expires: 'inaisha', alreadyExpired: 'muda umeisha', inDays: 'siku {{n}}',
        dLeft: 'siku {{n}}', expired: 'muda umeisha',
        searchPh: 'Tafuta bidhaa…', fAll: 'Zote', fLow: 'Stoo Ndogo', fOut: 'Zimeisha',
        fExpiring: 'Zinazoisha', fRecent: 'Mpya', noMatch: 'Hakuna bidhaa zinazolingana.',
        thProduct: 'Bidhaa', thStock: 'Stoo', thSell: 'Bei ya Kuuza', thCost: 'Gharama',
        thProfit: 'Faida', thStatus: 'Hali', thAction: 'Kitendo',
        pack: 'Pakiti', receive: 'Pokea', history: 'Historia', sell: 'Kuuza', cost: 'Gharama',
        recSearchPh: 'Tafuta bidhaa…', recPacks: 'Idadi (pakiti)', recPackPrice: 'Bei ya kununua kwa pakiti',
        recSupplier: 'Msambazaji (hiari)', recExpiry: 'Muda wa kuisha (hiari)',
        recNotesPh: 'Namba ya ankara, n.k.', recNow: 'Sasa', recPackSize: 'Ukubwa wa pakiti', recDateAuto: 'Tarehe: leo (kiotomatiki)',
        recBack: 'Rudi', recTotal: 'Jumla ya gharama',
        msgSelectProduct: 'Chagua bidhaa kwanza', msgEnterPacks: 'Weka pakiti ngapi',
        adjTitle: 'Rekebisha Stoo', adjCurrent: 'Stoo ya sasa', adjDelta: 'Marekebisho (tumia − kupunguza, mf. −2)',
        adjReason: 'Sababu', adjHint: 'Marekebisho husahihisha stoo tu — hayabadilishi mapato ya mauzo.',
        adjSave: 'Hifadhi marekebisho', msgBadDelta: 'Weka marekebisho yasiyo sifuri (mf. -2)',
        detCurrent: 'Stoo ya Sasa', detPack: 'Ukubwa wa Pakiti', detSell: 'Bei ya Kuuza', detCost: 'Gharama',
        detProfitPer: 'Faida / {{u}}', detValue: 'Thamani ya Stoo', detReceive: 'Pokea Stoo',
        detAdjust: 'Rekebisha Stoo', detEdit: 'Hariri Bidhaa', detActivity: 'Shughuli za Karibuni',
        detNoMoves: 'Hakuna mienendo bado.',
        moveOpening: 'Stoo ya mwanzo', moveReceived: 'Stoo imepokewa', moveSale: 'Mauzo',
        moveDamaged: 'Imeharibika', moveAdjustment: 'Marekebisho',
        reasonDamaged: 'Imeharibika', reasonExpired: 'Muda umeisha', reasonMissing: 'Imepotea',
        reasonPersonal: 'Matumizi binafsi', reasonCounting: 'Kosa la kuhesabu', reasonOther: 'Nyingine',
        msgReceived: 'Stoo imepokewa ✓ +{{n}} {{u}}', msgAdjusted: 'Stoo imerekebishwa ✓ sasa {{n}} {{u}}',
        msgMarkedDone: 'Imemalizika ✓ — pokea stoo hapa chini kujaza',
        msgProductGone: 'Bidhaa haikupatikana kwenye orodha ya stoo',
        statusOut: 'Imeisha', statusLow: 'Stoo Ndogo', statusOk: 'Ipo',
      },
      analytics: {
        title: 'Faida na Uchambuzi', revChart: 'Mapato ({{r}})', netChart: 'Faida halisi ({{r}})',
        bestSelling: 'Zinazouzwa sana (vipimo)', highestRevenue: 'Mapato ya juu',
        mostProfitable: 'Faida kubwa', slowMoving: 'Polepole',
        sold: 'vimeuzwa {{n}}', noData: 'Hakuna taarifa bado',
        thProduct: 'Bidhaa', thUnits: 'Vipimo', thRevenue: 'Mapato', thCogs: 'Gharama za bidhaa',
        thProfit: 'Faida', thMargin: 'Kiwango',
      },
      productForm: {
        addTitle: 'Ongeza Bidhaa', editTitle: 'Hariri Bidhaa', products: 'Bidhaa',
        name: 'Jina la bidhaa', namePh: 'mf. Coca-Cola 500ml', description: 'Maelezo',
        descPh: 'Eleza bidhaa…', sellPrice: 'Bei ya kuuza (TZS)', buyPrice: 'Bei ya kununua (TZS)',
        unit: 'Kipimo', bundleQty: 'Idadi ya pakiti (vipimo kwa pakiti)', bundlePh: '24 kwa katoni ya 24',
        curStock: 'Stoo ya sasa (vipimo)', reorder: 'Kiwango cha kuagiza', expiry: 'Tarehe ya kuisha (hiari)',
        category: 'Kipengele', unitCost: 'Gharama kwa kipimo', unitProfit: 'Faida kwa kipimo',
        example: 'Mf. nunua katoni 1 (chupa 24) kwa 18,000 → gharama 750 → uza 1,000 → faida 250/kipimo.',
        sizesStock: 'Saizi na Stoo', size: 'Saizi', totalStock: 'Jumla ya stoo', pairs: 'jozi',
        images: 'Picha', newImages: 'picha {{n}} mpya zimechaguliwa',
        cancel: 'Ghairi', save: 'Hifadhi Mabadiliko', create: 'Unda Bidhaa',
        msgUpdated: 'Bidhaa imesasishwa ✓', msgCreated: 'Bidhaa imeundwa ✓',
      },
      dmgAdmin: {
        title: 'Stoo Imeharibika', showReviewed: 'Onyesha zilizopitiwa', hideReviewed: 'Ficha zilizopitiwa',
        nothingPending: 'Hakuna kinachosubiri kupitilizwa ✓', reviewed: 'imepitilizwa ✓', markReviewed: 'Weka alama',
        msgReviewed: 'Imetiwa alama imepitilizwa ✓',
      },
      reports: {
        title: 'Ripoti', pdfTitle: 'Ripoti rasmi ya PDF — kipindi maalum',
        start: 'Tarehe ya mwanzo', end: 'Tarehe ya mwisho', secSales: 'Mauzo', secDebt: 'Deni/Mkopo', secStock: 'Sto',
        download: 'Pakua PDF', msgDates: 'Chagua tarehe ya mwanzo na ya mwisho',
        msgOrder: 'Tarehe ya mwisho isiwe kabla ya ya mwanzo', msgSections: 'Chagua kipengele angalau kimoja',
        msgDownloaded: 'Ripoti imepakuliwa ✓',
        hint: 'Jumla zinalingana na dashibodi kwa kipindi hicho. Madeni ni ya sasa; mauzo na makusanyo ni ya tarehe zilizochaguliwa.',
        closings: 'Mafungo ya kila siku', noClosings: 'Hakuna ripoti za mafungo bado',
        noClosingsDesc: 'Muuzaji akituma mafungo ya siku, yataonekana hapa kwa mapitio.',
        thDate: 'Tarehe', thShopkeeper: 'Muuzaji', thExpected: 'Inayotarajiwa', thActual: 'Halisi',
        thDiff: 'Tofauti', thReview: 'Mapitio', review: 'Kagua', reviewed: 'Mafungo yamepitilizwa ✓',
        blkDaily: 'Ripoti ya kila siku', blkSummary: 'Muhtasari wa siku 30', blkStock: 'Arifa ya stoo', blkExpiry: 'Arifa ya kuisha muda',
        noData: 'Hakuna taarifa bado.', copyReport: 'Nakili ripoti',
      },
      activity: { title: 'Kumbukumbu za Shughuli', system: 'Mfumo' },
      assistant: {
        title: 'Msaidizi AI wa MauzoOS', desc: 'Uliza kuhusu mauzo, stoo, gharama, madeni na hali ya biashara.',
        s1: 'Biashara inaendeleaje leo?', s2: 'Tumeuza kiasi gani leo?',
        s3: 'Bidhaa gani zina stoo ndogo?', s4: 'Nani anatudai?', s5: 'Ninunue nini kujaza stoo?',
        tryAsking: 'Jaribu kuuliza:', placeholder: 'Uliza kuhusu biashara yako…', send: 'Tuma',
        listening: 'Ninasikiliza… zungumza sasa', thinking: 'Ninafikiria…',
        micVoice: 'Sauti', micLang: 'Lugha ya maikrofoni', mic: 'Sauti',
        micUnsupported: 'Sauti haiungwi mkono na kivinjari hiki — andika swali lako.',
        micHear: 'Sikikusikia — angalia ruhusa ya maikrofoni, au andika.',
        micBusy: 'Maikrofoni inatumika — jaribu tena.',
        aiFail: 'Samahani — sikuweza kujibu sasa hivi. POS yako inaendelea kufanya kazi kama kawaida.',
      },
      dash: {
        title: 'Dashibodi — leo', sales: 'Mauzo', revenue: 'Mapato', gross: 'Faida ghafi',
        expenses: 'Gharama', net: 'Faida halisi', cogs: 'Gharama za bidhaa', needsAttention: 'Inahitaji uangalizi',
        reorder: 'kiwango {{r}}', pendingExpenses: 'gharama {{n}} zinasubiri',
        unreviewedDamage: 'ripoti {{n}} za uharibifu hazijapitiwa',
        revChart: 'Mapato — siku 7 zilizopita', netChart: 'Faida halisi — siku 7 zilizopita',
      },
      admSales: {
        title: 'Mauzo', cardSales: 'Mauzo', cardRevenue: 'Mapato', cardGross: 'Faida ghafi',
        thDate: 'Tarehe', thShopkeeper: 'Muuzaji', thTotal: 'Jumla', thProfit: 'Faida', thAction: 'Kitendo',
        view: 'Angalia', invoice: 'Ankara', detTitle: 'Maelezo ya mauzo',
      },
      staff: {
        title: 'Akaunti za Wafanyakazi', fullName: 'Jina kamili', email: 'Barua pepe', phone: 'Simu',
        password: 'Nenosiri', role: 'Wadhifa', optShop: 'Muuzaji', optAdmin: 'Msimamizi',
        add: 'Ongeza mfanyakazi', thName: 'Jina', thEmail: 'Barua pepe', thPhone: 'Simu', thRole: 'Wadhifa',
        thStatus: 'Hali', thAction: 'Kitendo', admin: 'Msimamizi', shopkeeper: 'Muuzaji',
        you: '(wewe)', current: 'Akaunti yako', enable: 'Wezesha', disable: 'Zima',
        active: 'Hai', disabled: 'Imezimwa',
        noStaff: 'Hakuna wafanyakazi bado', noStaffDesc: 'Ongeza mfanyakazi wako wa kwanza hapo juu.',
        createdAdmin: 'Akaunti ya msimamizi imeundwa', createdShop: 'Akaunti ya muuzaji imeundwa',
        statusUpdated: 'Hali imesasishwa',
      },
      products: {
        title: 'Bidhaa', add: '+ Ongeza Bidhaa', searchPh: 'Tafuta bidhaa…',
        noProducts: 'Hakuna bidhaa', noProductsDesc: 'Ongeza bidhaa yako ya kwanza.',
        thProduct: 'Bidhaa', thCategory: 'Kipengele', thBuying: 'Kununua', thSelling: 'Kuuza',
        thStock: 'Stoo', thActions: 'Vitendo', edit: 'Hariri', delete: 'Futa',
        delTitle: 'Futa bidhaa', delConfirm: 'Una uhakika unataka kufuta {{name}}? Haiwezi kurudishwa.',
        cancel: 'Ghairi', msgDeleted: 'Bidhaa imefutwa',
      },
      cats: {
        title: 'Vipengele', add: '+ Ongeza Kipengele', nProducts: 'bidhaa {{n}}',
        noDesc: 'Hakuna maelezo', edit: 'Hariri', delete: 'Futa',
        modalAdd: 'Ongeza Kipengele', modalEdit: 'Hariri Kipengele', name: 'Jina', description: 'Maelezo',
        saving: 'Inahifadhi…', save: 'Hifadhi',
        msgCreated: 'Kipengele kimeundwa ✓', msgUpdated: 'Kipengele kimesasishwa ✓',
        delConfirm: 'Futa kipengele "{{name}}"?', msgDeleted: 'Kipengele kimefutwa',
      },
      dmg: {
        title: 'Ripoti Uharibifu', product: 'Bidhaa', select: 'Chagua…',
        quantity: 'Idadi', reason: 'Sababu',
        rExpired: 'Muda umeisha', rDamaged: 'Imeharibika', rSpoiled: 'Imeoza',
        rBroken: 'Imevunjika', rLost: 'Imepotea', rOther: 'Nyingine',
        photo: 'Picha *', submit: 'Tuma ripoti',
        msgPhoto: 'Picha inahitajika', msgReported: 'Uharibifu umeripotiwa ✓ stoo imesasishwa',
      },
      closing: {
        title: 'Funga Siku', expected: 'Inayotarajiwa (mauzo ya leo)', counted: 'Kilichohesabiwa',
        cashLabel: 'Taslimu iliyohesabiwa', cashPh: 'Hesabu droo…',
        submit: 'Tuma mafungo', msgSubmitted: 'Mafungo yametumwa ✓',
      },
      invoice: {
        back: 'Rudi', print: 'Chapisha', receipt: 'Ankara ya Mauzo', receiptNo: 'Namba ya ankara',
        date: 'Tarehe', item: 'Bidhaa', qty: 'Idadi', price: 'Bei', total: 'Jumla',
        thanks: 'Asante kwa kununua nasi!',
      },
      today: {
        revenueToday: 'Mapato ya leo', sales: 'mauzo', noSales: 'Hakuna mauzo bado',
        firstSale: 'Rekodi mauzo yako ya kwanza ya leo.', sale: 'Mauzo',
        nLines: 'mistari {{n}}', tapInvoice: 'gusa kwa ankara',
      },
      stock: {
        title: 'Sto', searchPh: 'Tafuta…', noProducts: 'Hakuna bidhaa',
        noMatch: 'Hakuna kinacholingana.', available: '{{n}} zinapatikana', outOfStock: 'Zimeisha',
      },
      common: {
        save: 'Hifadhi', cancel: 'Ghairi', delete: 'Futa', edit: 'Hariri', back: 'Rudi',
        view: 'Angalia', all: 'Zote', total: 'Jumla', date: 'Tarehe', noteOpt: 'Maelezo (hiari)',
        search: 'Tafuta…', loading: 'Inapakia…', confirm: 'Thibitisha', name: 'Jina',
        phone: 'Simu', amount: 'Kiasi', status: 'Hali', action: 'Kitendo',
      },
      sale: {
        title: 'Rekodi Mauzo', searchPh: 'Tafuta bidhaa…', noProducts: 'Hakuna bidhaa',
        noMatch: 'Hakuna kinacholingana na utafutaji.', outOfStock: 'Zimeisha zote.',
        left: '{{n}} zimebaki', inSale: 'Kwenye mauzo', qty: 'Idadi', add: 'Ongeza',
        confirmSale: 'Thibitisha mauzo', total: 'Jumla', payMethod: 'Njia ya malipo',
        mobRef: 'Kumbukumbu ya malipo ya simu', mobRefPh: 'mf. MPK2X9F4K12 · namba ya muamala',
        mobRefHint: 'Hiari, lakini inarahisisha ulinganifu na statement ya M-Pesa.',
        customer: 'Mteja', existing: 'Aliyepo', newCustomer: '+ Mteja Mpya',
        loadingCustomers: 'Inapakia wateja…', noDebtors: 'Hakuna wadeniwa bado — tumia + Mteja Mpya hapo juu.',
        selectCustomer: 'Chagua mteja…', alreadyOwes: 'Mteja huyu tayari anadaiwa {{amount}}.',
        owes: 'anadaiwa', custNamePh: 'Jina la mteja *', phoneOpt: 'Simu (hiari)',
        amountPaid: 'Kiasi kilicholipwa', dueOpt: 'Tarehe ya kulipa (hiari)',
        wTotal: 'Jumla', wPaid: 'amelipa', wDebt: 'deni',
        dueHint: 'Acha tarehe wazi kama hamkuahidi tarehe. Deni lisilo na tarehe halitahesabiwa kuchelewa.',
        photoOpt: 'Picha ya ushahidi (hiari)', photoReq: 'Picha ya ushahidi *',
        confirmBtn: 'Thibitisha mauzo · {{total}} · {{method}}',
        recordedDebt: 'Mauzo yamekamilika ✓ deni {{amount}}', recorded: 'Mauzo yamekamilika ✓ {{total}}',
        nItems: 'bidhaa {{n}}',
        msgAddProduct: 'Ongeza bidhaa angalau moja',
        msgFullPaid: 'Kiasi kilicholipwa kinatosha jumla — tumia mauzo ya kawaida badala yake',
        msgPhoto: 'Picha ya ushahidi inahitajika',
        msgStockOnly: '{{name}}: zimebaki {{n}} tu',
        msgEnterName: 'Weka jina la mteja',
        msgSelectDebtor: 'Chagua mteja anayekopa',
      },
      paymethods: { cash: 'Taslimu', mobile: 'Malipo ya simu', credit: 'Mkopo' },
      home: {
        title: 'Nyumbani kwa Muuzaji',
        tileSaleD: 'Mauzo ya haraka na picha ya ushahidi', tileTodayD: 'Mauzo yako ya leo',
        tileStockD: 'Idadi tu', tileDamageD: 'Imeharibika / imeisha muda',
        tileExpensesD: 'Rekodi gharama za uendeshaji', tileClosingD: 'Hesabu taslimu na inayotarajiwa',
        restockRequested: 'Ombi la stoo limetumwa ✓ msimamizi ataarifiwa',
        runningLow: 'Zinakaribia kuisha — omba kujaza stoo',
        left: 'zimebaki', requested: 'Imeombwa ✓', request: 'Omba',
        viewAllStock: 'Angalia stoo yote →', waitingApproval: 'Inasubiri idhini ya msimamizi',
        expenses: 'gharama', expense1: 'gharama', damageReports: 'ripoti za uharibifu', damageReport1: 'ripoti ya uharibifu',
      },
      login: {
        tagline: 'MauzoPOS · Mfumo rahisi wa POS kwa maduka madogo',
        hero: 'Duka lako lote, katika mfumo mmoja rahisi.',
        heroSub: 'Mauzo, stoo, madeni na gharama — rekodi kwa sekunde, eleweka waziwazi, kutoka simu yoyote.',
        featSaleT: 'Mauzo ya haraka', featSaleD: 'Rekodi mauzo ya taslimu, simu na mkopo kwa sekunde.',
        featStockT: 'Stoo live', featStockD: 'Viwango vya stoo, arifa na upokeaji — kila wakati.',
        featRepT: 'Ripoti wazi', featRepD: 'Faida, gharama na madeni — kwa maelezo rahisi.',
      },
      nav: {
        dashboard: 'Dashibodi', sales: 'Mauzo', analytics: 'Uchambuzi', products: 'Bidhaa',
        categories: 'Vipengele', inventory: 'Stoo', expenses: 'Gharama', damage: 'Uharibifu',
        debt: 'Deni/Mkopo', reports: 'Ripoti', assistant: 'Msaidizi AI', activity: 'Shughuli',
        staff: 'Wafanyakazi', home: 'Nyumbani', recordSale: 'Rekodi Mauzo', today: 'Mauzo ya Leo',
        stock: 'Sto', reportDamage: 'Ripoti Uharibifu', dailyClosing: 'Funga Siku',
      },
      header: {
        adminPanel: 'Jopo la Msimamizi', shopkeeper: 'Muuzaji', welcome: 'Karibu, {{name}}',
        admin: 'Msimamizi', shopkeeperFallback: 'Muuzaji', newSale: 'Mauzo Mapya', logout: 'Toka',
        lightMode: 'Mandhari ya mchana', darkMode: 'Mandhari ya usiku',
      },
    },
    seo: {
      home: 'M&E PUB — Ingia Katika Mchezo Wako',
      about: 'Kuhusu Sisi — MauzoPOS',
      cart: 'Rukoba Wako — MauzoPOS',
      checkout: 'Malipo — MauzoPOS',
      contact: 'Wasiliana Nasi — MauzoPOS',
      login: 'Ingia — MauzoPOS',
      shop: 'Numua Viatu — MauzoPOS',
      track: 'Fuatilia Agizo Lako — MauzoPOS',
      wishlist: 'Orodha yangu — MauzoPOS',
      orders: 'Maagizo Yangu — MauzoPOS',
      profile: 'Profili Yangu — MauzoPOS',
      notFound: 'Ukurasa Haupatikani — MauzoPOS',
      orderDetail: 'Agizo {{number}} — MauzoPOS',
      product: '{{name}} — MauzoPOS',
    },
  },
};

export const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('gsky_lang') || 'en');
  useEffect(() => {
    localStorage.setItem('gsky_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = translations[lang] || translations.en;
  const toggle = () => setLang((l) => (l === 'en' ? 'sw' : 'en'));

  const tf = (template, vars = {}) =>
    template ? template.replace(/\{\{(\w+)\}\}/g, (m, k) => (k in vars ? String(vars[k]) : m)) : template;

  const statusLabel = (key) => (t.status && t.status[key] ? t.status[key] : key);

  return (
    <LanguageContext.Provider value={{ lang, t, tf, statusLabel, toggle, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
